#!/bin/sh


battery_percentage=$(cat /sys/class/power_supply/BAT1/capacity)
battery_status=$(cat /sys/class/power_supply/BAT1/status)

if [[ $battery_status = "Charging" ]]; then
    battery_status="󱐋"
else
    battery_status=""
fi

scale=$(( ($battery_percentage * 10) / 100 ))
scale=$(( scale < 1 ? 1 : (scale > 10 ? 10 : scale) ))

case $scale in
    1)
        icon="󰂃"
       ;;
    2)
        icon="󰁺"
        ;;
    3)
        icon="󰁻"
        ;;
    4)
        icon="󰁼"
        ;;
    5)
        icon="󰁽"
        ;;
    6)
        icon="󰁾"
        ;;
    7)
        icon="󰁿"
        ;;
    8)
        icon="󰂀"
        ;;
    9)
        icon="󰂁"
        ;;
    10)
        icon="󰁹"
        ;;


    esac

    echo "${battery_status}${icon}${battery_percentage}%"
