#!/bin/zsh

# # Obtener la carpeta seleccionada
main_folder=$(ls -F -1 /home/kuro/Desktop/kuro/projects | grep / | fzf)


target=$(ls -F -1 /home/kuro/Desktop/kuro/projects/$main_folder | grep / )

if [[ $target == "" ]]; then
    echo $main_folder
    exit 1
fi

target="$main_folder/$(echo $target | fzf)"
echo $target
