#!/bin/bash

ip_address=$(/bin/cat $DOTFILES_PATH/scripts/kuro/target | awk '{print $1}')
machine_name=$(/bin/cat $DOTFILES_PATH/scripts/kuro/target | awk '{print $2}')

if [ $ip_address ] && [ $machine_name ]; then
    echo "󰯐 $ip_address - $machine_name"
else
    echo ""
fi
